AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FacebookHooksQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "facebook-hooks"

Outputs:
  QueueURL:
    Description: "URL of new Amazon SQS Queue"
    Value:
      Ref: "FacebookHooksQueue"
  QueueARN:
    Description: "ARN of new AmazonSQS Queue"
    Value:
      Fn::GetAtt:
        - "FacebookHooksQueue"
        - "Arn"
  QueueName:
    Description: "Name of new Amazon SQS Queue"
    Value:
      Fn::GetAtt:
        - "FacebookHooksQueue"
        - "QueueName"